augment_flag: true
augment_margin: 16
batch_size: 64
bn_decay: 0.9
bn_mom: 0.9
ce_loss: false
class_num: 85742
dataset_size: 490623
embed_size: 256
epoch_num: 100
fc7_use_bias: true
fc_type: GDC
fine_weights: None
gpu_num: 1
image_size: 112
input_shape:
- 112
- 112
- 3
keep_prob: 0.4
log: ./output_dir/20191116-210447/log.txt
logits_margin: 0.5
logits_scale: 64.0
loss_type: softmax
momentum: 0.9
net_act: prelu
net_blocks:
- 2
- 8
- 16
- 4
network: fmobilefacenet
output_dir: ./output_dir/20191116-210447
outputs_dir: ./output_dir
pretrained_model: /data/hhd/InsightFace-tensorflow/output/20190120-133421/checkpoints/ckpt-m-140000
restore_weights: ''
softmax_layer: softmax_pred
step_per_epoch: 7666
train_data: faces_webface_112x112
val_bn_train: false
val_data:
  agedb_30: agedb_30.bin
  calfw: calfw.bin
  cfp_ff: cfp_ff.bin
  cfp_fp: cfp_fp.bin
  cplfw: cplfw.bin
  lfw: lfw.bin
val_freq: 2000
weight_decay: 0.0005
