# use
softmax_layer: "softmax_pred"

dataset_size: 5822653

batch_size: 512
gpu_capacity: 64

train_data: './data/faces_emore'
val_data: {'agedb_30': './data/faces_emore/agedb_30.bin', 'lfw': './data/faces_emore/lfw.bin',
           'cfp_ff': './data/faces_emore/cfp_ff.bin', 'cfp_fp': './data/faces_emore/cfp_fp.bin',
           'calfw': './data/faces_emore/calfw.bin', 'cplfw': './data/faces_emore/cplfw.bin',
           'vgg2_fp': './data/faces_emore/vgg2_fp.bin'}

output_dir: './model_dir/log'

model_config: "model_dir/model.json"
model_weights: "model_dir/weights.h5"

# filter


# model params
backbone_type: resnet_v2_m_50
loss_type: softmax
out_type: E

image_size: 112
embd_size: 512
class_num: 85742
embed_num: 512


# hyper params
bn_decay: 0.9
keep_prob: 0.4
weight_decay: !!float 5e-4
logits_scale: 64.0
logits_margin: 0.5
momentum: 0.9


# run params
val_bn_train: False
augment_flag: True
augment_margin: 16

gpu_num: 1

epoch_num: 20
step_per_epoch: 100000

val_freq: 2000

# paths
pretrained_model: '/data/hhd/InsightFace-tensorflow/output/20190120-133421/checkpoints/ckpt-m-140000'

